version 2.1

jobs: 
  build:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: creating virtual env of python
          command: |
          python3 -m venv venv
          . venv/bin/activate
      - run:
          name: installing the packages and executing the program
          command: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python billing_system.py

workflows:
  build_now:
    jobs:
      - build
