version: 2.1

jobs:
  #Job to build the main file
  build:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Install dependencies and execute program
          command: |
            python3 -m venv venv
            . venv/bin/activate
            python3 -m pip install --upgrade pip
            pip install -r requirements.txt
            python3 billing_system.py

  # Job to execute test case 1
  test-job-1:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Execute first test case
          command: python3 test_billing_system_1.py

  #Job to execute test case 2
  test-job-2:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Execute second test case
          command: python3 test_billing_system_2.py

  #Job to create artifact
  create-artifact:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - run:
          name: Creating an artifact and zip it
          command: tar -cvzf /tmp/tmp_package.tar .
      - store_artifacts:
          path: /tmp/tmp_package.tar

  #Job to save and restore cache
  build-cache:
    docker:
      - image: cimg/python:3.11.4
    steps:
      - checkout
      - restore_cache:
          name: Restore the pip cache
          keys:
            - deps1-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: create virtual environment and install the dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Execute program
          command: python3 billing_system.py
      - save_cache:
          name: Save the cache
          key: deps1-cache-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv

workflows:
  build_test_approve:
    jobs:
      - build
      - test-job-1:
          requires:
            - build
      - test-job-2:
          requires:
            - build
      - need-approval:
          type: approval
          requires:
            - test-job-1
            - test-job-2
      - create-artifact:
          requires:
            - need-approval

  schedule_cache_build_test:
    triggers:
      - schedule:
          cron: "0 11 * * *"
          filters:
            branches:
              only:
                - rohan_caselet

    jobs:
      - build-cache
      - test-job-1:
          requires:
            - build-cache
      - test-job-2:
          requires:
            - test-job-1
      - need-approval:
          type: approval
          requires:
            - test-job-2
      - create-artifact:
          requires:
            - need-approval
